openapi: 3.0.1
info:
  title: monster-aboleth
  x-cortex-tag: monster-aboleth
  x-cortex-custom-metadata:
    alignment: chaotic-good
    type: plant
    challenge_rating: 17
    legendary: false
    armor_class: 17
    hit_points: 160
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-aboleth
      alias: github-token-test
